---
- hosts: all
  become: true

  tasks:
  - name: create docker image using Dockerfile
    command: docker build -t simple-devops-image:latest .
    args:
      chdir: /opt/docker

  - name: create tag to image
    command: docker tag simple-devops-image:latest loveguptapp/simple-devops-image:latest

  - name: push image on to dockerhub
    command: docker push loveguptapp/simple-devops-image:latest

  - name: remove docker image from ansible server
    command: docker rmi simple-devops-image loveguptapp/simple-devops-image:latest
    ignore_errors: yes
...
